package com.fly.web.dao;

import com.fly.web.pojo.QuestionDO;
import java.util.List;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_question
     *
     * @mbg.generated Sun Aug 30 14:01:19 CST 2020
     */
    int deleteByPrimaryKey(Integer qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_question
     *
     * @mbg.generated Sun Aug 30 14:01:19 CST 2020
     */
    int insert(QuestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_question
     *
     * @mbg.generated Sun Aug 30 14:01:19 CST 2020
     */
    QuestionDO selectByPrimaryKey(Integer qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_question
     *
     * @mbg.generated Sun Aug 30 14:01:19 CST 2020
     */
    List<QuestionDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_question
     *
     * @mbg.generated Sun Aug 30 14:01:19 CST 2020
     */
    int updateByPrimaryKey(QuestionDO record);
}